### ISSUE TITLE
Error: ServerFaultCode: A specified parameter was not correct: startOffset

### ISSUE THREAD

**Issue by flyersa** [vexxhost/migratekit#24]
Hello,

trying migration script i did a first initial migrate. Then after a while it will copy incremental for like 80% and then i get:

Error: ServerFaultCode: A specified parameter was not correct: startOffset

and thats it. Any idea? Using latest migratekit and VDDK 8.0.3

If i do migrate and right away a cutover it works, will try direct cutover after while again if this also happens after alot of block changes on the source.

**Comment by mnaser** [comment]
Is it possible that you have another tool that is running backups by any chance at the same time that took a snapshot or is it a brief period of time where this is happening?

How big is the volume exactly?

**Comment by flyersa** [comment]
No i especially made this machines just for testing migratekit. Nothing else did run at this period and it happens with all of them. Its just 40GB

**Comment by francoisovh** [comment]
I had this error on vSphere 7.0U3 cause CBT was not activated on VM. I've also updated the VM hardware to last version supported (19).

**Comment by flyersa** [comment]
Yes its also 7.0U3. But CBT was activated, otherwise it complains befor already that no CBT is enabled. It should have the latest version since it was new VMs im sure i picked it. Will test a bit more

**Comment by michael-salo** [comment]
We've seen the same behaviour on some random VMs too, incremental copy was failing after ~80-83% completion. But at the same time VM on VMware was reporting error,  in VM console you could see something like this: 

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/57b88066-4dbd-4e02-aef6-2caabf0cf847">

Having moved(live migration) of VMs to different DataStore in VMware some VMs with that error were successfully moved over, but not all of them. I'll update this issue here if I find anything more. 

It's got to be something to do with VMware config or Datastore related, but not migratekit problem.

**Comment by jmussmann** [comment]
I think the problem is the calculation of startOffset of the next iteration. 

```go
startOffset += diskChangeInfo.StartOffset + diskChangeInfo.Length
```
"diskChangeInfo.StartOffset" should be global so I think the correct version is:

```go
startOffset = diskChangeInfo.StartOffset + diskChangeInfo.Length
```

I will create a pull request

**Comment by michael-salo** [comment]
I can give it a go tomorrow on VMs that I had seen this error on. I haven't figured out why it's happening to some VMs only, as I'd have expected it to be consistent for all disks/vmdks. We've moved over 300 VMs, but have seen issues on ~15-20 VMDKs so far, some we managed to fix by storage vmotion. @mnaser I'll try that fix that @jmussmann has shared and will update this thread once it's been tested out.

**Comment by mnaser** [comment]
Thank you so much!

It's cool you've moved 300 VMs so far :)

**Comment by jmussmann** [comment]
@mnaser in my tests it works.

@michael-salo you can use my docker container if you want: https://hub.docker.com/r/dorfpinguin/migratekit

As explanation:

The error only occurs if the DiskChangeInfo provides an area which does not reach to the end of the disk, which I think might happen if only allocated blocks changes. Then the startOffset becomes greater than the diskSize, which is an invalid parameter for QueryChangedDiskAreas. 

As far as I understand the documentation even the outer for loop should not be necessary, because with a 0 startOffset QueryChangedDiskAreas  should compute all changes. Then the whole startOffset computation and the break condition is not needed anymore.

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/8f96698a-0e7b-4d67-bb6c-d18a1d101540/ef536a47-27cd-481a-90ef-76b38e75353c/doc/GUID-2C25F80D-3FBD-4397-BB4B-AE08527399C8.html

**Comment by mnaser** [comment]
@jmussmann

**Comment by jmussmann** [comment]
> @jmussmann
> 
> https://vdc-repo.vmware.com/vmwb-repository/dcr-public/5bc36046-6569-42b8-a60d-4b175d91fa9d/56a2807a-c2a0-4971-8cd8-ee5440e17b19/doc/vim.VirtualMachine.html#queryChangedDiskAreas
> 
> > Start Offset in bytes at which to start computing changes. Typically, callers will make multiple calls to this function, starting with startOffset 0 and then examine the "length" property in the returned DiskChangeInfo structure, repeatedly calling queryChangedDiskAreas until a map forthe entire virtual disk has been obtained.
> 
> So that's why I've done the loop, now technically the `startOffset` in the response should match up with the one we sent in the request, so I feel like the number should stay in sync.. in theory

Ok, then the loop makes sense to me now. But the returned startOffset seems to be the global one. So the starting offset of the next call has to be set and by "diskChangeInfo.StartOffset + diskChangeInfo.Length" and not incremented by this.

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/5bc36046-6569-42b8-a60d-4b175d91fa9d/56a2807a-c2a0-4971-8cd8-ee5440e17b19/doc/vim.VirtualMachine.DiskChangeInfo.html

**Comment by mnaser** [comment]
I'm running into the issue but I think you are right about this.

**Comment by mnaser** [comment]
Thanks for the fix @jmussmann !

**Comment by michael-salo** [comment]
I tested it today and moved 5 VMs that couldn't move before that fix works for sure!
